# Shared Secrets HARDCODED, Don't do this in PROD please! :D
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
stringData:
  username: "user4mongo"
  password: "pwd4mongo"
type: Opaque
---
# MongoDB Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0.5
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: password
          resources:
            requests:
              cpu: "100m"
              memory: "300M"
            limits:
              cpu: "100m"
              memory: "300M"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
  type: ClusterIP
---
# Application Deployment (webapp: RottenPotatoes)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotten-potatoes
spec:
  selector:
    matchLabels:
      app: rotten-potatoes
  template:
    metadata:
      labels:
        app: rotten-potatoes
    spec:
      containers:
        - name: rotten-potatoes
          image: gm50x/rotten-potatoes:v1
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_DB
              value: admin
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: password
          resources:
            requests:
              cpu: "50m"
              memory: "100M"
            limits:
              cpu: "50m"
              memory: "100M"
---
apiVersion: v1
kind: Service
metadata:
  name: rotten-potatoes
spec:
  selector:
    app: rotten-potatoes
  ports:
    - appProtocol: TCP
      port: 8080
      targetPort: 5000
  type: LoadBalancer
